# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-17 20:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codesnippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 17, 20, 54, 4, 970088, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 17, 20, 54, 4, 970088, tzinfo=utc)),
        ),
    ]
